<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="POU_3" Id="{3c04b035-fb99-4029-9ab8-cede714cb956}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM POU_3
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU_3">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>