<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="POU_3" Id="{3c04b035-fb99-4029-9ab8-cede714cb956}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM POU_3
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="METH" Id="{d96f3746-3f0c-4727-8dcf-3719e1d16356}">
      <Declaration><![CDATA[METHOD METH : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="POU_3">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="POU_3.METH">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>